# Generated by Django 3.2.6 on 2021-09-01 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('fintransid', models.CharField(blank=True, max_length=200, null=True)),
                ('extid', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.CharField(blank=True, max_length=10, null=True)),
                ('phonepartyid', models.CharField(blank=True, max_length=20, null=True)),
                ('payermessage', models.CharField(blank=True, max_length=200, null=True)),
                ('reason', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('comm', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
