# Generated by Django 3.2.6 on 2021-09-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='ptype',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
