# Generated by Django 3.2.6 on 2021-09-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payments_ptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='amountPaid'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='comm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='community'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='fintransid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='transactionId'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payermessage',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='paymentRemarks'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='phonepartyid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='phoneNumber'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='ptype',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='productType'),
        ),
    ]
