# Generated by Django 3.2.6 on 2021-09-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_rename_paymentremarks_payments_numberofbuckets'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='paid_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Paid By'),
        ),
    ]
